name: Run tests

on:
  push:
    branches: [development, master]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  run:
    uses: moosetechnology/.github/.github/workflows/run-tests.yml@main
    with:
      pharo-versions: "['Pharo64-13', 'Pharo64-14']"
    secrets: inherit
